spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/orders
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092

inventory:
  url: http://inventory-service:8081