spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092